<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dooby" failures="1" tests="4" name="Create Customer API Test" time="2.102" errors="0" timestamp="2021-05-05T17:51:50 IST">
  <testcase classname="com.dooby.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIwithInValidSecretKey" time="1.294">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.dooby.testcases.CreateCustomerTest.ValidateCreateCustomerAPIwithInValidSecretKey(CreateCustomerTest.java:40)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- ValidateCreateCustomerAPIwithInValidSecretKey -->
  <testcase classname="com.dooby.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIwithValidSecretKey" time="0.553"/>
  <testcase classname="com.dooby.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIwithValidSecretKey" time="0.563"/>
  <testcase classname="com.dooby.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIwithValidSecretKey" time="0.76"/>
</testsuite> <!-- Create Customer API Test -->
