<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-05T17:51:48 IST" name="Suite" finished-at="2021-05-05T17:51:51 IST" duration-ms="3018">
    <groups>
    </groups>
    <test started-at="2021-05-05T17:51:48 IST" name="Create Customer API Test" finished-at="2021-05-05T17:51:50 IST" duration-ms="2102">
      <class name="com.dooby.testcases.CreateCustomerTest">
        <test-method signature="ValidateCreateCustomerAPIwithInValidSecretKey(java.util.Hashtable)[pri:0, instance:com.dooby.testcases.CreateCustomerTest@7a362b6b]" started-at="2021-05-05T17:51:48 IST" name="ValidateCreateCustomerAPIwithInValidSecretKey" data-provider="exceldata" finished-at="2021-05-05T17:51:49 IST" duration-ms="1294" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=at1@zmail.com, name=Atul, description=adding fourth customer to API}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.dooby.testcases.CreateCustomerTest.ValidateCreateCustomerAPIwithInValidSecretKey(CreateCustomerTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIwithInValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIwithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.dooby.testcases.CreateCustomerTest@7a362b6b]" started-at="2021-05-05T17:51:49 IST" name="ValidateCreateCustomerAPIwithValidSecretKey" data-provider="exceldata" finished-at="2021-05-05T17:51:50 IST" duration-ms="563" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=ahpr1@zmail.com, name=ashutosh11, description=adding second customer to API}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIwithValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIwithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.dooby.testcases.CreateCustomerTest@7a362b6b]" started-at="2021-05-05T17:51:49 IST" name="ValidateCreateCustomerAPIwithValidSecretKey" data-provider="exceldata" finished-at="2021-05-05T17:51:50 IST" duration-ms="760" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=imr1@zmail.com, name=imraan11, description=adding third customer to API}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIwithValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIwithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.dooby.testcases.CreateCustomerTest@7a362b6b]" started-at="2021-05-05T17:51:49 IST" name="ValidateCreateCustomerAPIwithValidSecretKey" data-provider="exceldata" finished-at="2021-05-05T17:51:50 IST" duration-ms="553" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rao1@zmail.com, name=Raunak11, description=adding first customer to API}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIwithValidSecretKey -->
      </class> <!-- com.dooby.testcases.CreateCustomerTest -->
    </test> <!-- Create Customer API Test -->
    <test started-at="2021-05-05T17:51:50 IST" name="Delete Customer API Test" finished-at="2021-05-05T17:51:51 IST" duration-ms="691">
      <class name="com.dooby.testcases.DeleteCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.dooby.testcases.DeleteCustomerTest@39de3d36]" started-at="2021-05-05T17:51:47 IST" name="setUp" finished-at="2021-05-05T17:51:48 IST" duration-ms="459" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.dooby.testcases.DeleteCustomerTest@39de3d36]" started-at="2021-05-05T17:51:50 IST" name="deleteCustomer" data-provider="exceldata" finished-at="2021-05-05T17:51:51 IST" duration-ms="688" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_JPqsc8luSwsMQV}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID mismatch !! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID mismatch !! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.dooby.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
      </class> <!-- com.dooby.testcases.DeleteCustomerTest -->
    </test> <!-- Delete Customer API Test -->
  </suite> <!-- Suite -->
</testng-results>
